<?php
        $apiKey="rzp_test_IdEeEz7ZLHdIl0";
        include 'connection.php';
        session_start();
        $sid=$_SESSION['login_id'];
        $cusamount=$_GET['amount'];
        
        
        $query="select tbl_registration.*,tbl_package.*,tbl_booking.* from tbl_registration,tbl_booking,tbl_package WHERE tbl_booking.package_id=tbl_package.package_id and tbl_registration.login_id=tbl_booking.login_id and tbl_booking.login_id='$sid'";
        $result=mysqli_query($con,$query);
        while ($row = mysqli_fetch_assoc($result)) {
            $id=$row['booking_id'];
            $amount=$row['package_price'];
            $lid=$row['login_id'];
            $pid=$row['package_id'];
            $email=$row['emails'];
            $name=$row['firstname'];

            

        }

        //$totalamount=$amount + $cusamount;
        
?>
<form action="paymentaction.php?bid=<?php echo $id ?>&&amt=<?php echo $cusamount ?>&&lid=<?php echo $lid ?>&&pid=<?php echo $pid  ?>&&eml=<?php echo $email ?>" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $cusamount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay"
    data-name="Smart Tourist Guiding System"//project name
    data-description="Make journey Unforgettable "
    data-image=""
    data-prefill.name="<?php echo $name;?>"
    data-prefill.email="<?php echo $email ?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form> 

<!--style>
.razorpay-payment-button { display:none; }
</style>


<script type="text/javascript">
  $(document).ready(function(){
    $('.razorpay-payment-button').click();

});
</script-->
