<?php
        $apiKey="rzp_test_IdEeEz7ZLHdIl0";
        include 'connection.php';
        session_start();
        $sid=$_SESSION['login_id'];
        $cusamount=$_GET['amount'];
        $cid=$_GET['cid'];
        
        
        $query="select tbl_registration.*,tbl_cab_booking.* from tbl_registration,tbl_cab_booking WHERE tbl_registration.login_id=tbl_cab_booking.login_id  and tbl_cab_booking.login_id='$sid' and tbl_cab_booking.cabbook_id='$cid';";
        $result=mysqli_query($con,$query);
        while ($row = mysqli_fetch_assoc($result)) {
            $email=$row['emails'];
            $name=$row['firstname'].' '.$row['lastname'];
            $did=$row['driver_id'];

            

        }

        //$totalamount=$amount + $cusamount;
        
?>
<form action="taxipaymentaction.php?cid=<?php echo $cid ?>&&amt=<?php echo $cusamount ?>&&did=<?php echo $did ?>&&lid=<?php echo $sid ?>&&eml=<?php echo $email ?>" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $cusamount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay"
    data-name="Smart Tourist Guiding System"//project name
    data-description="Make journey Unforgettable "
    data-image=""
    data-prefill.name="<?php echo $name;?>"
    data-prefill.email="<?php echo $email ?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form> 

<!--style>
.razorpay-payment-button { display:none; }
</style>


<script type="text/javascript">
  $(document).ready(function(){
    $('.razorpay-payment-button').click();

});
</script-->
